# default config.yml
# eggArthropodPercentage is out of 1.0
eggArthropodPercentage: 0.03
eggLootingPercentage: 0.02
eggEntityIDList: ["donkey", "mule", "bat", "pig", "sheep", "cow", "chicken", "squid", "wolf", "mooshroom", "ocelot", "horse", "rabbit", "llama", "parrot", "villager", "turtle", "dolphin", "polar_bear", "cod", "salmon", "tropical_fish", "pufferfish"]
eggDebug: false
eggRemoveDrops: true
